import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PROJECT_ROOT = path.resolve(__dirname, "../..");
const E2E_WORKDIR = path.join(PROJECT_ROOT, "supabase-e2e");
const APP_DIR = path.join(PROJECT_ROOT, "app");

const EXCLUDED_SERVICES = [
	"studio",
	"realtime",
	"storage-api",
	"imgproxy",
	"edge-runtime",
	"logflare",
	"vector",
	"supavisor",
	"postgres-meta",
];

interface SupabaseStatus {
	API_URL: string;
	DB_URL: string;
	ANON_KEY: string;
	SERVICE_ROLE_KEY: string;
	INBUCKET_URL?: string;
}

function getBasePort(): number {
	return Number.parseInt(process.env.CONDUCTOR_PORT || "3300", 10);
}

function generateSupabaseConfig(basePort: number): string {
	const apiPort = basePort + 1;
	const dbPort = basePort + 2;
	const mailpitPort = basePort + 3;
	const smtpPort = basePort + 4;
	const shadowPort = basePort + 5;
	const studioPort = basePort + 6;
	const analyticsPort = basePort + 7;
	const poolerPort = basePort + 8;
	const edgeRuntimePort = basePort + 9;

	return `# Auto-generated config for E2E tests. Do not edit manually.
# Generated by app/e2e/supabase-setup.ts from CONDUCTOR_PORT=${basePort}
project_id = "abode-e2e-${basePort}"

[api]
enabled = true
port = ${apiPort}
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = ${dbPort}
shadow_port = ${shadowPort}
major_version = 17

[db.pooler]
enabled = false
port = ${poolerPort}
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = false
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true

[studio]
enabled = true
port = ${studioPort}
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = ${mailpitPort}
smtp_port = ${smtpPort}

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:${basePort}"
additional_redirect_urls = ["https://127.0.0.1:${basePort}", "http://localhost:${basePort}/auth/confirm", "http://127.0.0.1:${basePort}/auth/confirm"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.rate_limit]
email_sent = 100
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 100
token_verifications = 100
web3 = 30

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.email.template.confirmation]
subject = "Confirm Your Email"
content_path = "./supabase/templates/confirmation.html"

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
otp_length = 6
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[auth.external.apple]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
redirect_uri = ""
url = ""
skip_nonce_check = false
email_optional = false

[auth.web3.solana]
enabled = false

[auth.third_party.firebase]
enabled = false

[auth.third_party.auth0]
enabled = false

[auth.third_party.aws_cognito]
enabled = false

[auth.third_party.clerk]
enabled = false

[auth.oauth_server]
enabled = false
authorization_url_path = "/oauth/consent"
allow_dynamic_registration = false

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = ${edgeRuntimePort}
deno_version = 2

[analytics]
enabled = true
port = ${analyticsPort}
backend = "postgres"

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"
`;
}

export function startTestSupabase(): void {
	const basePort = getBasePort();
	const config = generateSupabaseConfig(basePort);
	const configPath = path.join(E2E_WORKDIR, "supabase", "config.toml");

	fs.mkdirSync(path.dirname(configPath), { recursive: true });
	fs.writeFileSync(configPath, config);

	const excludeFlag = EXCLUDED_SERVICES.join(",");

	execSync(`supabase start --workdir "${E2E_WORKDIR}" -x ${excludeFlag}`, {
		stdio: "inherit",
		cwd: PROJECT_ROOT,
	});
}

export function stopTestSupabase(): void {
	execSync(
		`supabase stop --workdir "${E2E_WORKDIR}" --no-backup 2>/dev/null || true`,
		{
			stdio: "inherit",
			cwd: PROJECT_ROOT,
		},
	);
}

export function getTestSupabaseStatus(): SupabaseStatus {
	const output = execSync(
		`supabase status --workdir "${E2E_WORKDIR}" -o json`,
		{
			encoding: "utf-8",
			cwd: PROJECT_ROOT,
		},
	);
	return JSON.parse(output);
}

export function runPrismaMigrations(databaseUrl: string): void {
	execSync("bunx prisma migrate deploy", {
		stdio: "inherit",
		cwd: APP_DIR,
		env: {
			...process.env,
			DATABASE_URL: databaseUrl,
			DIRECT_URL: databaseUrl,
		},
	});
}

export function createAdminClient(
	apiUrl: string,
	serviceRoleKey: string,
): import("@supabase/supabase-js").SupabaseClient {
	// Dynamic import to avoid loading at module level
	// eslint-disable-next-line @typescript-eslint/no-require-imports
	const { createClient } = require("@supabase/supabase-js");
	return createClient(apiUrl, serviceRoleKey, {
		auth: {
			autoRefreshToken: false,
			persistSession: false,
		},
	});
}
