/** Collapse whitespace the way rendered text reads, for exact matching */
export function normalizeLabel(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export const UI_LABELS_PATH = "src/lib/analytics/ui-labels.generated.ts";

/** Source of the generated labels module, so the generator and its staleness test agree */
export function renderUiLabelsModule(labels: string[]): string {
  return [
    "// Generated by scripts/generate-ui-labels.ts — do not edit.",
    "// UI copy that autocapture may record as click text; see scrub-event.ts.",
    "",
    `export const UI_LABELS: readonly string[] = ${JSON.stringify(labels, null, 2)};`,
    "",
  ].join("\n");
}
