import { EXPORT_FORMAT, EXPORT_FORMAT_VERSION } from "./serialize";

const count = (n: number, noun: string) => `${n} ${noun}${n === 1 ? "" : "s"}`;

/** The README.md at the root of every export, explaining what's inside */
export function buildExportReadme({
  exportedAt,
  instanceUrl,
  itemCount,
  roomCount,
  bookCount,
  bookmarkCount,
  fileCount,
}: {
  exportedAt: Date;
  instanceUrl: string;
  itemCount: number;
  roomCount: number;
  bookCount: number;
  bookmarkCount: number;
  fileCount: number;
}): string {
  return `# Your abode export

Exported from ${instanceUrl} on ${exportedAt.toISOString()}.

${[
  count(itemCount, "item"),
  count(roomCount, "room"),
  count(bookCount, "book"),
  count(bookmarkCount, "saved link"),
  count(fileCount, "stored file"),
].join(
  ", ",
)} (Any file that couldn't be copied in is listed in \`missing-files.txt\`, in the last part if your export was split.)

If your export downloaded as several parts (\`…-part-1-of-3.zip\` and so on), each unzips into its own folder. Part 1 is the main folder, starting with this README and \`abode.json\`; each later part (\`…-part-2\` and so on) holds the rest, mostly more of \`files/\`. To put everything in one place, move everything inside each later part's folder into the main folder, merging its \`files\` folder into the main one. That's where \`abode.json\` and the Markdown expect them.

## What's in here

| File | What it's for |
| --- | --- |
| \`abode.json\` | Everything, in one machine-readable file: your profile, rooms and every item with its details, notes, highlights and locations. The complete copy — use it to move to another abode instance, or to build your own tools. |
| \`items/<kind>/*.md\` | One Markdown file per item, with its details as frontmatter (properties). Readable in any text editor and drops straight into Obsidian or Logseq. |
| \`bookmarks.html\` | Every saved web link, with a folder per room. Import it into any browser or bookmarking service (Raindrop, Pinboard, Linkding, …). |
| \`files/\` | Your uploads, scans (each page, plus its colour original), covers and saved images, in a folder per item (\`files/<item id>/\`). \`abode.json\` and the Markdown point to them. If you uploaded a profile picture, it's in \`files/profile/\`. |
| \`books.csv\` | Your books in Goodreads' export format, including reading status, dates, ratings and reviews. StoryGraph, Hardcover and most book apps import it. |

## Notes on the data

- \`abode.json\` has \`"format": "${EXPORT_FORMAT}"\` and \`"version": ${EXPORT_FORMAT_VERSION}\`. Dates are ISO 8601 (UTC).
- Book ratings are stored out of 10 in \`abode.json\` (so half-stars work) and shown out of 5 everywhere else.
- In \`books.csv\`, text starting with \`=\`, \`+\`, \`-\` or \`@\` has an apostrophe added in front so spreadsheets don't run it as a formula. If an app you import into keeps the apostrophe, you can remove it.
- Smart rooms keep their filters in the same form as abode's search box (e.g. \`@tag:design\`); their item list is a snapshot of what matched when you exported.
- \`aiTags\`, descriptions, text found in images (OCR) and colours were generated by abode; \`userTags\` and \`notes\` are yours.
- \`missing-files.txt\` (if present) lists any file that couldn't be copied in. Videos saved from YouTube, X or Instagram are linked, not downloaded.
`;
}
